### ISSUE TITLE
Card Details has top border radius

### ISSUE THREAD

**Issue by yuriceschin** [amagitechnologies/react-native-card-animated-modal#3]
Hi,
the component is beautiful and works well, but I noticed that in the card details area there is a border radius at the top that it's impossible to hide.
You can see it if you put a color background in the card detail.
Is it possibile to avoid it?
Thanks

**Comment by archieherbias** [comment]
Will check on this and will be updating it but that should be possible and easy fix.

**Comment by archieherbias** [comment]
Hi @yuriceschin , there's a new prop `detailsContainerStyle` where you can customize the styling for the rendered details area of the expanded card.

There's a default 20 border radius of the details area, so you can customize by providing
```
<CardList
    detailsContainerStyle={{
        borderRadius: 0
    }}
/>
```
